INBOX_TAG = 'inbox'
SENT_TAG = 'sent'
TRASH_TAG = 'trash'
ARCHIVE_TAG = 'archive'
# DEFAULT_LANGUAGE = 'en'
# DEFAULT_MAXIMUM_PAGE_SIZE = '20'
# DEFAULT_SHORTCUTS = nil
# DEFAULT_PICTURE = nil
# DEFAULT_SIGNATURE = nil
DEFAULT_OPTIONS = { language: 'en', maximum_page_size: '20', shortcuts: nil, picture: nil, signature: nil }